--p.125
--q1 사원이름이 S로 끝나는 데이터 찾기 
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO
FROM EMP
WHERE ENAME LIKE '%S';

--Q2 30번 부서에서 근무하고 있는 SALESMAN 찾기
SELECT EMPNO, ENAME,JOB,SAL,DEPTNO
FROM EMP
WHERE DEPTNO = 30
AND JOB = 'SALESMAN';

--Q3 집합 연산자를 사용하지않고 20,30번 부서에 급여가 2000을 초과하는 사원 찾기
SELECT EMPNO, ENAME,JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN (20,30)
AND SAL > 2000;

--Q3-2 집합 연산자를 사용해서 20,30번 부서에 급여가 2000을 초과하는 사원 찾기
SELECT EMPNO,ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN (20,30)
INTERSECT
SELECT EMPNO,ENAME,JOB,SAL, DEPTNO
FROM EMP
WHERE SAL > 2000;

--Q4 NOT BETWEEN A AND B 연산자를 쓰지 않고 급여값이 2000이상 3000이하의 범위 값찾기
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO
FROM EMP
WHERE SAL >=2000
OR SAL <=3000;

--Q5 사원 이름에 E가 포함되어 있는 30번 부서의 사원 중 급여가 1000~2000사이가 아닌 사원 찾기
SELECT ENAME, EMPNO,SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%'
AND DEPTNO = 30
AND SAL NOT BETWEEN 1000 AND 2000;

--Q6 추가 수당이 존재하지 않고 상급자가 있고 직책이 MANAGER, CLERK 인 사원중에서 이름에 두번째 자리가 L이 아닌 사원 찾기
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM,DEPTNO
FROM EMP
WHERE COMM IS NULL
AND JOB IN ('MANAGER','CLERK')
AND ENAME NOT LIKE '_L%';