<<<<<<< HEAD
CREATE table DEPT_TEMP
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP(DEPTNO,DNAME,LOC)
                      VALUES (50,'DATABASE','SEOUL');
                      
SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP
VALUES ( 60,'NETWORK','BUSAN');

SELECT * FROM DEPT_TEMP;

--명시적 NULL 삽입법
INSERT INTO DEPT_TEMP (DEPTNO,ENAME,LOC)
                        VALUES(70, 'WEB',NULL);
                        
 SELECT * from DEPT_TEMP;
 
 INSERT INTO DEPT_TEMP (DEPTNO,DNAME,LOC)
                        VALUES(80,'MOBILE','');
 SELECT  * FROM DEPT_TEMP;
 
 INSERT INTO DEPT_TEMP (DEPTNO,LOC)
                        VALUES ( 90, 'INCHEON');
                        
 SELECT * from DEPT_TEMP;
 
 CREATE TABLE EMP_TEMP
 AS SELECT * 
 FROM EMP;
 
SELECT * FROM EMP_TEMP;
 
 INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
            VALUES (9999,'홍길동','PRESIDENT',NULL, '2001/01/01',
            5000,1000,10);
            
 SELECT * FROM EMP_TEMP;
 
 INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
             VALUES ( 1111,'성춘향','MANAGER',9999,'2001-01-05',4000,NULL,20);
             
 SELECT * FROM EMP_TEMP;
 
 INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
 VALUES (2111,'이순신','MANAGER',9999,TO_DATE('07/01/2001','DD/MM/YY'),
        4000,NULL,20);
        
        SELECT * FROM EMP_TEMP;
       
INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (3111,'심청이','MANAGER', 9999,SYSDATE,4000,NULL,30);
SELECT * FROM EMP_TEMP;

CREATE TABLE DEPT_TEMP2
AS SELECT * from DEPT;

SELECT * from DEPT_TEMP2;

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';
SELECT * FROM DEPT_TEMP2;


ROLLBACK;

UPDATE DET_TEMP2
SET DNAME = 'DATABASE',
LOC = 'SEOUL'
WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;

CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP;

SELECT  * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

=======
CREATE table DEPT_TEMP
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP(DEPTNO,DNAME,LOC)
                      VALUES (50,'DATABASE','SEOUL');
                      
SELECT * FROM DEPT_TEMP;

INSERT INTO DEPT_TEMP
VALUES ( 60,'NETWORK','BUSAN');

SELECT * FROM DEPT_TEMP;

--명시적 NULL 삽입법
INSERT INTO DEPT_TEMP (DEPTNO,ENAME,LOC)
                        VALUES(70, 'WEB',NULL);
                        
 SELECT * from DEPT_TEMP;
 
 INSERT INTO DEPT_TEMP (DEPTNO,DNAME,LOC)
                        VALUES(80,'MOBILE','');
 SELECT  * FROM DEPT_TEMP;
 
 INSERT INTO DEPT_TEMP (DEPTNO,LOC)
                        VALUES ( 90, 'INCHEON');
                        
 SELECT * from DEPT_TEMP;
 
 CREATE TABLE EMP_TEMP
 AS SELECT * 
 FROM EMP;
 
SELECT * FROM EMP_TEMP;
 
 INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
            VALUES (9999,'홍길동','PRESIDENT',NULL, '2001/01/01',
            5000,1000,10);
            
 SELECT * FROM EMP_TEMP;
 
 INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
             VALUES ( 1111,'성춘향','MANAGER',9999,'2001-01-05',4000,NULL,20);
             
 SELECT * FROM EMP_TEMP;
 
 INSERT INTO EMP_TEMP (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
 VALUES (2111,'이순신','MANAGER',9999,TO_DATE('07/01/2001','DD/MM/YY'),
        4000,NULL,20);
        
        SELECT * FROM EMP_TEMP;
       
INSERT INTO EMP_TEMP(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (3111,'심청이','MANAGER', 9999,SYSDATE,4000,NULL,30);
SELECT * FROM EMP_TEMP;

CREATE TABLE DEPT_TEMP2
AS SELECT * from DEPT;

SELECT * from DEPT_TEMP2;

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';
SELECT * FROM DEPT_TEMP2;


ROLLBACK;

UPDATE DET_TEMP2
SET DNAME = 'DATABASE',
LOC = 'SEOUL'
WHERE DEPTNO = 40;
SELECT * FROM DEPT_TEMP2;

CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP;

SELECT  * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

>>>>>>> 5f480b9fdf80c02c50eb1bc3a63b35272afb86f9
SELECT * FROM EMP_TEMP2;