--Q1 사원이름이 다섯글자 이상이며 여섯글자 미만. 사원 번호 앞 두자리를 제외한 뒷자리 *로 채우기 
SELECT EMPNO,
    RPAD(SUBSTR(EMPNO,1,2),4,'*') AS MASKING_EMPNO,
    ENAME,
   RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS MASKING_ENAME
    FROM EMP
    WHERE LENGTH(ENAME)>=5
    and LENGTH(ENAME)<6;
    
    --Q2 평균 근무일은 21.5 하루 근무시간은 8 하루 급여와 시급 구하기
    SELECT EMPNO, ENAME,SAL
    ,TRUNC((SAL/21.5),2) AS DAY_PAY,ROUND((SAL/21.5/8),1)AS TIME_PAY
    FROM EMP;
   
   --Q3 3개월이 지난 월요일에 정직원이 됩니다.'YYYY-MM-DD' 형식으로 출력하기
   SELECT EMPNO, ENAME,HIREDATE,TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE,3),'월요일'),'YYYY-MM-DD') AS R_JOB,
   NVL(TO_CHAR(COMM),'N/A') AS COMM
   FROM EMP;
   
   --Q4 
   SELECT EMPNO, ENAME,MGR,
   CASE 
   WHEN MGR IS NULL THEN '0000'
   WHEN SUBSTR(MGR,1,2)=75 THEN '5555'
   WHEN SUBSTR(MGR,1,2)=76 THEN '6666'
   WHEN SUBSTR(MGR,1,2)=77 THEN '7777'
   WHEN SUBSTR(MGR,1,2)=78 THEN '8888'
   END AS CHG_MGR
   FROM EMP;

